added register team and display participants, teams
iiitv/hackathon-team-builder pull request #13
Opened 2017-01-17 15:09 UTC by arpit1997

added requiremements.txt
added register team view
added team and participant display
added team profile vew

2017-01-17 15:21 UTC, singhpratyush commented
You were not supposed to work on team profile view, weren't you?

If you still wish to add the same, assign yourself #9 and work on team edit view too.

2017-01-17 15:32 UTC, singhpratyush requested changes
Please consider the mentioned changes.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/models.py
> +        return self.user.first_name+self.user.last_name
Shouldn't it be
```python
    return self.user.first_name + ' ' + self.user.last_name
```

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/templates/participant.html
> +                </tr>
Add skills too.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/templates/teams.html
> +                </tr>
Add overall skills and member count too.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/urls.py
> +    url(r'^team/profile/(?P<team_name>[\S]+)/?$', views.team_profile, name='team-profile'),
Team names should be 4 to 64 chars long.
```python
    url(r'^team/profile/(?P<team_name>[a-zA-Z0-9\-]{4,64})/?$', views.team_profile, name='team-profile'),
```

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/views.py
> +	user = utils.get_login_user(request.COOKIES)
What is this diff for?

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/views.py
> +			team_name = team_name.replace(' ', '-', 32)
Not a good way. Just check team names for `[a-zA-Z0-9\-]{4,64}` and put up error if needed.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/views.py
> +					team = models.Team.objects.create(name=team_name, created_by=created_by, create_time=created_time,
`create_time` is managed internally by Django.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/views.py
> +					return HttpResponseRedirect('/')
`django.shortcuts.redirect` is already imported.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/views.py
> +			'user': None,
User will be required for headers here.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/views.py
> +	else:
Why not simply redirecting to `/team` in case he hasn't logged in.

2017-01-17 15:32 UTC, singhpratyush commented on teambuilder/web/views.py
> +		return HttpResponse('404 not found')
Use `404.html`.

2017-01-17 16:10 UTC, arpit1997 commented on teambuilder/web/views.py
> +	user = utils.get_login_user(request.COOKIES)
This might be a mistake. I will correct it.

2017-01-17 16:14 UTC, arpit1997 commented on teambuilder/web/views.py
> +			team_name = team_name.replace(' ', '-', 32)
What if a team name has spaces in it?
consider [this](http://stackoverflow.com/questions/497908/is-a-url-allowed-to-contain-a-space)

2017-01-17 17:06 UTC, singhpratyush commented on teambuilder/web/views.py
> +			team_name = team_name.replace(' ', '-', 32)
If you look at the regex that I've written, it doesn't allows spaces or any character that may be escaped as URL.

2017-01-17 17:29 UTC, arpit1997 commented on teambuilder/web/views.py
> +			team_name = team_name.replace(' ', '-', 32)
When team name is for example `fire n ice` then what will be the team profile url ?
Aren't we allowing spaces in the team names?

2017-01-18 01:19 UTC, singhpratyush commented on teambuilder/web/views.py
> +			team_name = team_name.replace(' ', '-', 32)
> Just check team names for `[a-zA-Z0-9\-]{4,64}`

If you look at the regex I'm talking about, we don't allow spaces.

2021-05-07 15:45 UTC, closed without merging